python test.py \
	--data_name "gsm8k" \
	--output_dir "$SAVE_DIR" \
	--model_name_or_path "/inspire/hdd/global_user/weilongxuan-253108120168/models/gpt2" \
	--seed 11 \
	--model_max_length 512 \
	--bf16 \
	--lora_r 128 --lora_alpha 32 --lora_init \
	--batch_size 128 \
	--greedy True \
	--num_latent 6 \
	--use_prj True \
	--prj_dim 768 \
	--prj_no_ln False \
	--prj_dropout 0.0 \
	--inf_latent_iterations 6 \
	--inf_num_iterations 1 \
	--remove_eos True \
	--use_lora True \
	--ckpt_dir "/inspire/qb-ilm2/project/neosmosis/weilongxuan-253108120168/codi/checkpoints/gpt2/gsm8k-aug/codi/gpt2-gsm8k-aug-codi/gpt2/ep_40/lr_0.003/seed_11"
